### ISSUE TITLE
Policy elements that are syntactically lists but semantically sets should have their order ignored

### ISSUE THREAD

**Issue by mjreed-wbd** [jen20/awspolicyequivalence#10] opened 2021-06-09 14:20 UTC
The AWS API seems to randomly reorder certain policy elements that are treated as sets (see https://github.com/hashicorp/terraform-provider-aws/issues/11801), so it would be helpful if there were at least an option to ignore order when comparing those elements. Actions, Principals, probably Resources . . . I'm trying to think of any AWS policy elements where order matters, actually, and not coming up with any.

**Comment by ewbankkit** [comment] 2021-06-10 13:01
Useful AWS documentation:

* [IAM JSON policy elements reference](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html)
* [Determining whether a request is allowed or denied within an account](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html#policy-eval-denyallow)

**Comment by RLuckom** [comment] 2021-06-11 15:10
> The AWS API seems to randomly reorder certain policy elements that are treated as sets (see [hashicorp/terraform-provider-aws#11801](https://github.com/hashicorp/terraform-provider-aws/issues/11801)), so it would be helpful if there were at least an option to ignore order when comparing those elements. Actions, Principals, probably Resources . . . I'm trying to think of any AWS policy elements where order matters, actually, and not coming up with any.

It ought* to be safe to assume that in any case where the API returns elements in a random order, the order is not significant.

*lol

**Comment by NiklasWagner** [comment] 2021-08-20 10:07
Hi,

I tried to debug this issue since we have the same issue in terraform with changes made outside of terraform. Turns out the `PoliciesAreEquivalent` function returns true correctly even when the order of the `Principal` list changes.

https://github.com/jen20/awspolicyequivalence/blob/8b377d2e0fe02b0b097741f61b33c029af6afd7f/aws_policy_equivalence.go#L50

So seems to be a issue with terraform handling the diff but I'm not sure why it doesn't work...

https://github.com/hashicorp/terraform-provider-aws/blob/5acf00216e10eaef2d153f2367f0746d4a57c6b8/aws/resource_aws_ecr_repository_policy.go#L38

**Comment by jen20** [comment] 2021-09-30 15:08
Hi folks, apologies for not addressing this before, I missed the notifications for it.

The original described desire is how this library has handled lists from the AWS API from the first commit - all arrays are compared as sets, since the ordering is not important. The code that achieves that performs equality on the internal set type is here:

https://github.com/jen20/awspolicyequivalence/blob/master/aws_policy_equivalence.go#L163-L167

And the creation of such sets for each of the compared policies is here (for example):

https://github.com/jen20/awspolicyequivalence/blob/master/aws_policy_equivalence.go#L175-L179

As per @NiklasWagner's comment, I believe this already works correctly from this library and whatever bug this is causing must originate elsewhere. Consequently, I'm going to close this issue as "cannot reproduce - behaves correctly".

If someone can provide a failing unit test demonstrating incorrect behaviour, _and a fix_, I can merge It and cut a release, however I am contractually obligated to not publish open source code currently so cannot do so myself.

**Closed as completed** 2021-09-30 15:11 UTC
